[package]
name    = "bitvec"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
bits = { path = "../../bits" }
fenwicktree = { path = "../../fenwicktree" }
num = { path = "../../num" }

[dev-dependencies]
