[package]
name    = "bits"
version = "0.1.0"
edition = "2021"
publish = false

# [lib]
# path = "lib.rs"

[features]
default = ["alloc"]
alloc = []

[dependencies]
num = { path = "../num" }

[dev-dependencies]
bitvec = { path = "./bitvec" }
quickcheck = "1"
quickcheck_macros = "1"
