on:
  workflow_call:

jobs:
  # For the PR title:
  # - the name of the primary package affected by the change goes before the colon
  # - the part after the colon uses the verb tense
  # - the verb after the colon is lowercase
  # - there is no trailing period
  title-regexp-match:
    name: Title regexp match
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          [[ "${{ github.event.pull_request.title }}" =~ ^[a-z]{1}[a-z/]*:\ [a-z]{1}.*[^.]$ ]]
