on:
  workflow_call:

jobs:
  bazel:
    name: Bazel
    runs-on: [ubuntu-22.04]
    env:
      BAZEL: bazel --output_user_root=/tmp/fuzz/
      BAZEL_ARGS: --config=fuzz
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache-fuzz
        with:
          path: |
            /tmp/fuzz
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - run: $BAZEL build $BAZEL_ARGS //build/rules/fuzzing/examples:memory_leaks
        name: Build

      # TODO: Test fuzzing targets
      # - run: $BAZEL test $BAZEL_ARGS //build/rules/fuzzing/examples:memory_leaks
