on:
  workflow_call:

env:
  BAZEL_COMMAND_ARGS: --config=fuzz
  BAZEL: bazel --output_user_root=/tmp/fuzz/

jobs:
  bazel:
    name: Bazel
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache-fuzz
        with:
          path: |
            /tmp/fuzz
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      # TODO: Test fuzzing targets
      - run: $BAZEL build $BAZEL_COMMAND_ARGS //...
        name: Build
