on:
  workflow_call:

jobs:
  bazel:
    name: Bazel
    runs-on: [ubuntu-22.04]
    env:
      BAZEL_OUTPUT_USER_ROOT: /tmp/fuzz/
      BAZEL_STARTUP_ARGS: --output_user_root=$BAZEL_OUTPUT_USER_ROOT
      BAZEL_COMMAND_ARGS: --config=fuzz --build_tag_filters=+fuzzing
      BAZEL: bazel $BAZEL_STARTUP_ARGS
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache-fuzz
        with:
          path: |
            $BAZEL_OUTPUT_USER_ROOT
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      # TODO: Test fuzzing targets
      - run: $BAZEL build $BAZEL_COMMAND_ARGS //...
        name: Build
