on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    uses: ./.github/workflows/testing.yaml
    with:
      os: ${{ matrix.os }}
  fuzzing:
    uses: ./.github/workflows/fuzzing.yaml
