name: Presubmit

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    strategy:
      matrix:
        # TODO: add macos-12
        os: [ubuntu-22.04]
        channel: [stable, nightly]
    uses: ./.github/workflows/testing.yaml
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.os }}
