on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  BAZEL_COMMAND_ARGS: --config=ci
  BAZEL: bazel --output_user_root=/tmp/ci/

jobs:
  bazel:
    name: Bazel
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          # bazelisk stores a bazel binary in the [UserCacheDir](https://pkg.go.dev/os#UserCacheDir).
          path: |
            $BAZEL_OUTPUT_USER_ROOT
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - run: echo "$XDG_CACHE_HOME"

      - name: Build
        run: $BAZEL build $BAZEL_COMMAND_ARGS //...

      - name: Test
        run: $BAZEL test $BAZEL_COMMAND_ARGS //...

      - name: Audit
        if: github.event_name == 'schedule'
        run: $BAZEL run $BAZEL_COMMAND_ARGS //tools/audit
